### ISSUE TITLE
Exception in thread "main" ElasticsearchException[Could not find plugin class [org.elasticsearch.metadatasearch.plugin.image.ImagePlugin]]; 

### ISSUE THREAD

**Issue by handsetvn** [usc-isi-i2/elasticsearch-image-features#2]
Verifying file:/home/longtran/Desktop/elasticsearch-image-features/target/image-metadata-search-0.0.1-SNAPSHOT.jar checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
Installed image into /home/longtran/Desktop/elasticsearch-2.1.1/plugins/image
longtran@longtran:~/Desktop/elasticsearch-2.1.1/bin$ ./elasticsearch
[2016-05-20 15:30:15,215][INFO ][node                     ] [Madison Jeffries] version[2.1.1], pid[4077], build[40e2c53/2015-12-15T13:05:55Z]
[2016-05-20 15:30:15,216][INFO ][node                     ] [Madison Jeffries] initializing ...
Exception in thread "main" ElasticsearchException[Could not find plugin class [org.elasticsearch.metadatasearch.plugin.image.ImagePlugin]]; nested: ClassNotFoundException[org.elasticsearch.metadatasearch.plugin.image.ImagePlugin];
Likely root cause: java.lang.ClassNotFoundException: org.elasticsearch.metadatasearch.plugin.image.ImagePlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:810)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:380)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:348)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:109)
	at org.elasticsearch.node.Node.<init>(Node.java:146)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

can anyone please help me?

**Comment by kasinath** [comment]
Hi!

I just noticed that the instructions on the readme are incorrect.

After you do the mvn  package step, please use the complete zipped archive that is generated inside the "target/releases" folder, not the jar file inside "target" folder. 

That should resolve this issue you face when you start your ES instance.
